# Generated by Django 4.0.4 on 2022-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiktamGroupChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgca_groups',
            name='group_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
