# Generated by Django 4.0.4 on 2022-04-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiktamGroupChatApp', '0002_rgca_groups_group_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='RgcaGroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active_member', models.BooleanField(default=True)),
                ('added_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rgca_group_members',
            },
        ),
        migrations.RenameModel(
            old_name='Rgca_groups',
            new_name='RgcaGroups',
        ),
    ]
