# Generated by Django 4.0.4 on 2022-04-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiktamGroupChatApp', '0004_alter_rgcagroups_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgcagroups',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
