# Generated by Django 4.0.4 on 2022-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiktamGroupChatApp', '0006_rgcagroupmembers_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RgcaGroupMessagesMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('receiver_id', models.IntegerField(blank=True, null=True)),
                ('received_at', models.BigIntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('is_liked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rgca_group_messages_mappings',
            },
        ),
        migrations.CreateModel(
            name='RgcaGroupMessges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('added_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rgca_group_messages',
            },
        ),
    ]
